version: '3'
services:
  mysql:
    image: mariadb:10.3.2
    # Full UTF-8 support
    command: ["mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--init-connect='SET NAMES utf8mb4;'",
      "--character-set-client-handshake=FALSE"
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE={{cookiecutter.repo_name}}
    ports:
      - 3306:3306
  {{cookiecutter.repo_name}}:
    build: .
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8080"]
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE={{cookiecutter.repo_name}}.settings
      - DATABASE_URL=mysql://root:pass@mysql:3306/{{cookiecutter.repo_name}}?charset=utf8mb4
    volumes:
      - .:/app
    ports:
      - 8080:8080
    links:
      - mysql:mysql
